name: CraftDotaS
main: me.crafter.mc.craftdotas.CraftDotaS
author: connection_lost
depend: [HolographicDisplays, ScoreboardAPI, ActionBarAPI, TitleAPI]
version: beta-0.3
description: >
             0w0
commands:
   dota:
      permission: dota.admin
      usage: |
         /dota